name = "fcpp_string"
version = "0.1.0"
license = "MIT"
author = "Will Dickson"
maintainer = "wbd@caltech.edu"
copyright = "Copyright 2022, Will Dickson"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[[test]]
name = 'strings'
source-dir = 'test'

[test.dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"

[install]
library = false
