name = "fcpp_string"
version = "0.1.0"
license = "MIT"
author = "Will Dickson"
maintainer = "wbd@caltech.edu"
copyright = "Copyright 2022, Will Dickson"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
